### ISSUE TITLE
folders are not found

### ISSUE THREAD

**Issue by Keldo** [songposter/sam-song.info#1]
When you click on the Twitter or FaceBook Login image, /twitter/login or /facebook/login are not found

There is nothing in the instructions about this.

Furthermore, in entry_view.php all images had to have a / added in front in order for the web service to find them.

as well as /login and /logout

Are these things missing from Github completely?

**Comment by mastacheata** [comment]
Can you be more specific about your problems?

It's been quite a while since I last set this up completely from scratch, so I might need a little more input.

This is actually a 1:1 copy of the code running on sam-song.info except for the config files.
And it should be noted that I'm running this in an Nginx/PHP-FPM setup while most people trying it and the instructions are targeted at an Apache webserver.

**Comment by mastacheata** [comment]
Maybe try this with a simpler .htaccess version (i.e. less exceptions to the rule)
Haven't tried Apache in years, so no guarantee.

```
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

**Comment by Hightechteam** [comment]
Thank you I will give this a try and let you know how it turns out.

**Comment by Keldo** [comment]
now, after Authorizing on Twitter it redirects to what is supposed to be http://domain.name/twitter but instead, it goes to index.php? Not logging a user in or allowing access to the pal script setup

**Comment by mastacheata** [comment]
Hmm, ok I thought Apache would automatically append the Path part, apparently it doesn't do that (anymore?)

Replace the second to last line by this:
```RewriteRule ^(.*)$ index.php?$1 [L]```

If that doesn't work either, there's always the option of NOT dropping the index.php from the path:
In application/config/config.php set the index_page option to index.html:
```$config['index_page'] = 'index.php';```

Other than these options, I can only forward you to Stackoverflow and other Codeigniter help sites/documents for guides on how the CoddeIgniter Framework works (just be careful, this is CodeIgniter v2, the new v3 and v4 versions are completely different and have only few in common with the old framework I used when building this site):

This might be helpful: http://www.farinspace.com/codeigniter-htaccess-file/

Their full CodeIgniter .htaccess file looks like this and has some advanced protection stuff inside, not sure if that is really needed or if this is just about hiding the fact that the website uses CodeIgniter:
```<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
### Canonicalize codeigniter URLs
# If your default controller is something other than
# "welcome" you should probably change this
RewriteRule ^(welcome(/index)?|index(\.php)?)/?$ / [L,R=301]
RewriteRule ^(.*)/index/?$ $1 [L,R=301]
# Removes trailing slashes (prevents SEO duplicate content issues)
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.+)/$ $1 [L,R=301]
# Enforce www
# If you have subdomains, you can add them to 
# the list using the "|" (OR) regex operator
RewriteCond %{HTTP_HOST} !^(www|subdomain) [NC]
RewriteRule ^(.*)$ http://www.domain.tld/$1 [L,R=301]
# Enforce NO www
#RewriteCond %{HTTP_HOST} ^www [NC]
#RewriteRule ^(.*)$ http://domain.tld/$1 [L,R=301]
###
# Removes access to the system folder by users.
# Additionally this will allow you to create a System.php controller,
# previously this would not have been possible.
# 'system' can be replaced if you have renamed your system folder.
RewriteCond %{REQUEST_URI} ^system.*
RewriteRule ^(.*)$ /index.php/$1 [L]
# Checks to see if the user is attempting to access a valid file,
# such as an image or css document, if this isn't true it sends the
# request to index.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]
</IfModule>
<IfModule !mod_rewrite.c>
# Without mod_rewrite, route 404's to the front controller
ErrorDocument 404 /index.php
</IfModule>
```

**Comment by Keldo** [comment]
Now it just redirects to index.php when my Twitter app send them back to /twitter/ about to just give you access so you can see whats up

BTW: sam-song.info is not posting to Twitter anymore from my account for some reason

**Comment by mastacheata** [comment]
Get in touch via the Ticket System on sam-song.info for a more private conversation and I'll be glad to have a look.
These redirect problems usually happen if the redirect URL generated by the app and the one you stated in the twitter application details mismatch. Sometimes it's just a missing trailing slash.

**Comment by mastacheata** [comment]
> BTW: sam-song.info is not posting to Twitter anymore from my account for some reason

That is a bit too vague to help with. Tell me your screenname and I can probably tell you within a few minutes what's the reason for that. (Feel free to use the Ticket system for that as well. Just don't expect any replies tonight anymore. I'm off to bed now. It's 02.30 over here)
